# Generated by Django 4.2.9 on 2024-01-25 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0001_initial'),
        ('auteurs', '0002_auteur_fokontany_auteur_secteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='auteur',
            name='geolocalisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='localization.geolocalization'),
        ),
    ]
